### ISSUE TITLE
cosmos-sdk does not build anymore

### ISSUE THREAD

**Issue by sponnet** [Colm3na/DAppNodePackage-cosmos#5]
Hi,

The build of the SDK fails currently :

```
Building cosmos.public.dappnode.eth
Step 1/37 : FROM golang:alpine AS cosmos-build
 ---> 3024b4e742b0
Step 2/37 : ENV PACKAGES ca-certificates curl make git libc-dev bash gcc linux-headers eudev-dev python
 ---> Using cache
 ---> 5355ca9c2e29
Step 3/37 : ENV COSMOS_VERSION v0.34.7
 ---> Using cache
 ---> 18f77aad2579
Step 4/37 : RUN apk add --no-cache $PACKAGES
 ---> Using cache
 ---> 33162c8ee3d5
Step 5/37 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 46914b4441d1
Step 6/37 : RUN git clone https://github.com/cosmos/cosmos-sdk.git &&     cd cosmos-sdk &&     git fetch --tags &&     git checkout $COSMOS_VERSION
 ---> Using cache
 ---> 33f18413e086
Step 7/37 : WORKDIR /usr/src/app/cosmos-sdk
 ---> Using cache
 ---> 89fb0f9e8537
Step 8/37 : RUN make tools &&     make install
 ---> Running in b64eb2ef0970
go install -mod=readonly ./cmd/gosum/
go: updates to go.mod needed, disabled by -mod=readonly
make: *** [scripts/Makefile:60: /go/bin/gosum] Error 1
ERROR: Service 'cosmos.public.dappnode.eth' failed to build: The command '/bin/sh -c make tools &&     make install' returned a non-zero code: 2
Error: Command failed: /bin/sh -c docker-compose -f *.yml build
```
What I already tried:

1. tried installing from IPFS - but even after adding your peer it didn't download
2. I modified the Dockerfile & tried building the head revision of the sdk instead of the specific version -> didn't work either

There are no clear inststuctions on the cosmos site on how to build it.

We are interested in adding support for this package to the AVADO box ( https://ava.do ) we can also help propagating the IPFS data better... Feel free to reach out for some support from our side

Im also available in our AVADO channel -> https://t.me/joinchat/F_LlkBLEoDrFioPNviEpsQ

Thx

**Comment by wimel** [comment]
Cosmos-hub2 is [finished](https://github.com/cosmos/launch#cosmos-hub-upgrade-2), [pull request](https://github.com/Colm3na/DAppNodePackage-cosmos/pull/6) for hub3 is waiting for review.

For the _"no clear instructions on the Cosmos site"_ comment, you can check the install instructions on Cosmos Github from [Gaia](https://github.com/cosmos/gaia/blob/master/docs/gaia-tutorials/installation.md) or [Sdk](https://github.com/cosmos/cosmos-sdk) if you have problems with the installation.
